### PR TITLE
Update chalk to latest

### PR DESCRIPTION
**Pull request by yunzhu-li**
This updates `chalk` to latest for new features that helps with colored output in automated CI/CD pipelines.

### CODE REVIEW

**Comment by yunzhu-li** [comment]
cc @Emmawaterman

**Review by Emmawaterman — APPROVED** [review]
LGTM

**Comment by yunzhu-li** [comment]
Hi @namuol, would you mind taking a look? It's a one-liner change that will help us. Thanks!

**Comment by namuol** [comment]
I'll need to bump the version and publish to `npm` still -- thanks for the contribution 👍 🙇

**Comment by namuol** [comment]
Okay @yunzhu-li @Emmawaterman -- Latest version is available on `npm` as `0.7.1` -- thanks again!

**Comment by yunzhu-li** [comment]
Thank you @namuol 🎉

**Pull request merged**
